name: 'Auto PR fork'
author: 'Sidharth Ajithkumar'
description: 'A github action to create a PR from a fork to the upstream'
branding:
  icon: 'arrow-up-circle'
  color: 'green'

runs:
    using: 'node12'
    main: 'dist/index.js'